-- Tabla para el perfil del negocio
CREATE TABLE IF NOT EXISTS perfil_negocio (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre_negocio VARCHAR(255) NOT NULL,
    razon_social VARCHAR(255),
    cuit VARCHAR(20),
    condicion_iva VARCHAR(50),
    rubro VARCHAR(100),
    telefono VARCHAR(20),
    whatsapp VARCHAR(20),
    email VARCHAR(100),
    sitio_web VARCHAR(255),
    instagram VARCHAR(100),
    facebook VARCHAR(255),
    direccion VARCHAR(255),
    ciudad VARCHAR(100),
    provincia VARCHAR(100),
    codigo_postal VARCHAR(10),
    pais VARCHAR(100) DEFAULT 'Argentina',
    logo VARCHAR(255),
    mensaje_ticket TEXT,
    mostrar_logo_ticket TINYINT(1) DEFAULT 1,
    mostrar_direccion_ticket TINYINT(1) DEFAULT 1,
    mostrar_cuit_ticket TINYINT(1) DEFAULT 1,
    horarios JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
